### ISSUE TITLE
Not working for 1.15.2

### ISSUE THREAD

**Issue by Frettarix** [G07cha/MineflayerArmorManager#3]
Hi,

I found out it's not working for 1.15.2 and wrote a fix, can you give me permissions to push a branch so I can contribute? ;)

**Comment by G07cha** [comment]
Hi @Frettarix, that's great, thanks for your contribution! You can fork the repo and create a pull request from your fork, here is an example: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by G07cha** [comment]
Should be fixed in 1.0.0, thanks for your contribution @Frettarix!
