### ISSUE TITLE
Netherite armour unsupported

### ISSUE THREAD

**Issue by Slord6** [G07cha/MineflayerArmorManager#8]
As per title, giving the bot Netherite armor has no effect

**Comment by G07cha** [comment]
Indeed, mineflayer added support for 1.16 fairly recently, I'll update it later today, thanks for reporting!

**Comment by Slord6** [comment]
No worries. Thanks!

**Comment by G07cha** [comment]
Added support for netherite armor in v1.1.0

**Comment by Slord6** [comment]
Great, cheers!
